name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          post_compile: "cp main.pdf recipe_cards.pdf"
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest PDF"
          files: |
            recipe_cards.pdf
      - name: Fix release body text
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_name: latest
          body: PDF for printable 3x5 inch recipe cards
