name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y poppler-utils tree
      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          post_compile: "cp build/main.pdf recipe_cards.pdf"
      - name: Export per-card images
        run: ./export_cards.sh
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest PDF"
          files: |
            recipe_cards.pdf
      - name: Push PDF and card images to pages
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: |
            recipe_cards.pdf
            card/*.jpg
          destination_repo: 'OlliSaarikivi/homepage'
          destination_branch: 'master'
          user_email: 'olli.saarikivi@iki.fi'
          user_name: 'Olli Saarikivi'
          commit_message: 'Update recipe cards PDF and images to latest release'
