name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apt-get update && apt-get install -y poppler-utils tree

      - name: Build PDF with latexmk
        run: latexmk

      - name: Copy built PDF for release
        run: cp build/main.pdf recipe_cards.pdf

      - name: Export per-card images
        run: ./export_cards.sh

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest PDF"
          files: |
            recipe_cards.pdf

      - name: Push PDF and card images to pages
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: |
            recipe_cards.pdf
            card/*.jpg
          destination_repo: 'OlliSaarikivi/homepage'
          destination_branch: 'master'
          user_email: 'olli.saarikivi@iki.fi'
          user_name: 'Olli Saarikivi'
          commit_message: 'Update recipe cards PDF and images to latest release'
